"""Phase 3 Orchestrator Service for ProjectPilot AI.

Coordinates:
1. Normal autonomous specialist execution (Phase 1).
2. Controlled Reviewer feedback & self-correction loop (Phase 2).
3. Autonomous Issue Recovery & Replanning (Phase 3).

Phase 3 Features:
- Connects existing Report Issue workflow to the Orchestrator control layer.
- Deterministic recovery classification:
  * NO_ARTIFACT_CHANGE
  * PLAN_RECOVERY
  * ARCHITECTURE_RECOVERY
  * HUMAN_DECISION_REQUIRED
  * MANUAL_INTERVENTION_REQUIRED
- Targeted recovery (modifies only earliest affected upstream stage).
- Dependency-aware invalidation (Architecture changes invalidate Plan/Review/Tests; Plan changes invalidate Review/Tests).
- Human-in-the-loop decisions without hallucinating facts.
- Manual intervention handling for physical/hardware defects with user confirmation.
- Bounded recovery: max 2 recovery attempts per issue.
- Concurrency safety: mutual exclusion between normal autonomous pipeline and issue recovery.
- Targeted verification test scenarios generated by Test Agent.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from typing import Any, Callable

from app.agents.architecture_agent import architecture_agent
from app.agents.planner_agent import planner_agent
from app.agents.requirement_agent import requirement_agent
from app.agents.reviewer_agent import reviewer_agent
from app.agents.test_agent import test_agent
from app.schemas import (
    ArchitectureResponse,
    DecisionRecord,
    EngineeringMemory,
    HumanDecisionPrompt,
    InvalidationRecord,
    IssueAnalysisResponse,
    IssueRecord,
    ManualInterventionPrompt,
    OrchestratorRun,
    OrchestratorState,
    PlannerResponse,
    ProjectContext,
    RecoveryRecord,
    RequirementsResponse,
    RetrievedMemory,
    ReviewResponse,
    TestResponse,
)
from app.services.memory_service import memory_service

logger = logging.getLogger("orchestrator_service")

STAGE_SEQUENCE = [
    ("Requirements", "Requirement Agent"),
    ("Architecture", "Architecture Agent"),
    ("Execution Plan", "Planner Agent"),
    ("Review", "Reviewer Agent"),
    ("Testing", "Test Agent"),
]


class OrchestratorService:
    def __init__(
        self,
        projects: dict[str, ProjectContext],
        requirements_store: dict[str, RequirementsResponse],
        architecture_store: dict[str, ArchitectureResponse],
        plan_store: dict[str, PlannerResponse],
        review_store: dict[str, ReviewResponse],
        test_store: dict[str, TestResponse],
        orchestrator_store: dict[str, OrchestratorRun],
        activity_store: dict[str, list[dict[str, Any]]],
        save_db_fn: Callable[[], None],
        now_iso_fn: Callable[[], str],
        issues_store: dict[str, list[IssueRecord]] | None = None,
    ):
        self.projects = projects
        self.requirements_store = requirements_store
        self.architecture_store = architecture_store
        self.plan_store = plan_store
        self.review_store = review_store
        self.test_store = test_store
        self.orchestrator_store = orchestrator_store
        self.activity_store = activity_store
        self.save_db = save_db_fn
        self.now_iso = now_iso_fn
        self.issues_store = issues_store if issues_store is not None else {}
        self.requirement_agent = requirement_agent
        self.architecture_agent = architecture_agent
        self.planner_agent = planner_agent
        self.reviewer_agent = reviewer_agent
        self.test_agent = test_agent
        self.memory_service = memory_service

    def _retrieve_and_apply_memory(
        self,
        project: ProjectContext,
        agent_name: str,
        run: OrchestratorRun,
        issue_context: dict[str, Any] | None = None,
    ) -> str | None:
        """Retrieves advisory engineering memories for the agent and logs to activity store."""
        if agent_name in ("Requirement Agent", "Requirements"):
            return None

        retrieved = self.memory_service.retrieve_relevant_memories(
            project,
            target_agent=agent_name,
            issue_context=issue_context,
            max_results=3,
            threshold=0.35,
        )
        if not retrieved:
            return None

        existing_ids = {rm.memory.memory_id for rm in run.retrieved_memories}
        for rm in retrieved:
            if rm.memory.memory_id not in existing_ids:
                run.retrieved_memories.append(rm)
                existing_ids.add(rm.memory.memory_id)

        for rm in retrieved:
            self.activity_store.setdefault(project.id, []).insert(0, {
                "agent": agent_name,
                "action": "Retrieved Engineering Memory",
                "provider": "System Memory",
                "model": "Deterministic Matcher",
                "status": "completed",
                "duration_ms": 2,
                "summary": f"Retrieved lesson {rm.memory.memory_id} (Relevance {int(rm.relevance_score * 100)}%): {rm.reason_retrieved}",
            })

        return self.memory_service.format_memory_for_prompt(retrieved)

    def _store_recovery_lesson(
        self,
        project: ProjectContext,
        target_issue: IssueRecord,
        classification: str,
        target: str,
        actions_taken: list[str],
        verification_summary: str,
    ) -> None:
        """Extracts and stores a reusable engineering lesson from a successful issue recovery."""
        cat_map = {
            "ARCHITECTURE_RECOVERY": "architecture",
            "PLAN_RECOVERY": "planning",
            "MANUAL_INTERVENTION_REQUIRED": "hardware",
            "NO_ARTIFACT_CHANGE": "operational",
            "HUMAN_DECISION_REQUIRED": "requirements",
        }
        category = cat_map.get(classification, "architecture")
        techs = []
        if project.tech_stack:
            techs.extend([t.strip() for t in project.tech_stack.split(",") if t.strip()])

        self.memory_service.store_lesson(
            category=category,
            problem_pattern=target_issue.analysis.issue_summary or target_issue.description,
            diagnosis="; ".join(target_issue.analysis.likely_causes) if target_issue.analysis.likely_causes else target_issue.description,
            successful_action="; ".join(actions_taken) if actions_taken else "; ".join(target_issue.analysis.recommended_fix),
            verification_summary=verification_summary,
            source_project_id=project.id,
            source_issue_id=target_issue.id,
            technologies=techs,
            affected_component_types=target_issue.analysis.affected_components or [],
            initial_confidence=0.85,
        )

    def _store_self_correction_lesson(
        self,
        project: ProjectContext,
        target_agent: str,
        corrected_risks: list[dict[str, Any]],
        summary: str,
    ) -> None:
        """Stores a lesson from successful Reviewer self-correction."""
        category = "architecture" if "Architecture" in target_agent else "planning"
        techs = []
        if project.tech_stack:
            techs.extend([t.strip() for t in project.tech_stack.split(",") if t.strip()])

        risk_titles = [r.get("title", "") for r in corrected_risks if r.get("title")]
        risk_details = [r.get("detail", "") for r in corrected_risks if r.get("detail")]

        self.memory_service.store_lesson(
            category=category,
            problem_pattern="; ".join(risk_titles) if risk_titles else "Reviewer blocking finding",
            diagnosis="; ".join(risk_details) if risk_details else "Identified potential engineering failure mode during review",
            successful_action=summary,
            verification_summary="Self-correction verified and passed subsequent Reviewer re-evaluation",
            source_project_id=project.id,
            technologies=techs,
            initial_confidence=0.85,
        )

    def get_or_create_run(self, project_id: str) -> OrchestratorRun:
        run = self.orchestrator_store.get(project_id)
        if not run:
            run = OrchestratorRun(project_id=project_id, state=OrchestratorState.IDLE)
            self.orchestrator_store[project_id] = run

        # Synchronize completed stages from current persistence
        completed = []
        if self.requirements_store.get(project_id):
            completed.append("Requirements")
        if self.architecture_store.get(project_id):
            completed.append("Architecture")
        if self.plan_store.get(project_id):
            completed.append("Execution Plan")
        if self.review_store.get(project_id):
            completed.append("Review")
        if self.test_store.get(project_id):
            completed.append("Testing")
        run.completed_stages = completed

        # If all 5 completed and not running and not in recovery, mark as COMPLETED
        if (
            len(completed) == 5
            and not run.is_running
            and run.state not in (OrchestratorState.PAUSED, OrchestratorState.FAILED)
            and run.recovery_state in ("IDLE", "RECOVERY_COMPLETED")
        ):
            run.state = OrchestratorState.COMPLETED
            if not run.completed_at:
                run.completed_at = self.now_iso()

        return run

    def start(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)

        # Concurrency safety: cannot start normal run while issue recovery is actively running
        if run.active_issue_id and run.recovery_state in ("RECOVERING", "DIAGNOSING", "REVIEWING", "VERIFYING", "EVALUATING"):
            raise ValueError("Cannot start autonomous run while issue recovery is active")

        run.active_issue_id = ""
        run.recovery_state = "IDLE"
        run.recovery_type = ""
        run.recovery_target = ""
        run.recovery_attempt = 0
        run.manual_intervention_required = False
        run.manual_intervention_prompt = None

        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.failed_stage = ""
        run.last_error = ""
        run.error_message = ""
        run.human_input_required = False
        run.human_decision_prompt = None
        run.review_iteration = 1
        run.correction_count = 0
        run.max_corrections = 2
        run.correction_target = ""
        run.review_decision = ""
        run.unresolved_findings = []
        run.started_at = self.now_iso()
        run.completed_at = ""
        run.execution_count = 0
        self.save_db()
        return run

    def retry(self, project_id: str) -> OrchestratorRun:
        """Retry must rerun ONLY the failed stage, then proceed through remaining missing stages."""
        run = self.get_or_create_run(project_id)
        failed = run.failed_stage

        # Invalidate only the specific failed stage artifact if present
        if failed in ("Requirement Agent", "Requirements"):
            self.requirements_store.pop(project_id, None)
        elif failed in ("Architecture Agent", "Architecture"):
            self.architecture_store.pop(project_id, None)
        elif failed in ("Planner Agent", "Execution Plan"):
            self.plan_store.pop(project_id, None)
        elif failed in ("Reviewer Agent", "Review"):
            self.review_store.pop(project_id, None)
        elif failed in ("Test Agent", "Testing"):
            self.test_store.pop(project_id, None)

        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.failed_stage = ""
        run.last_error = ""
        run.error_message = ""
        run.human_input_required = False
        run.human_decision_prompt = None
        self.save_db()
        return run

    def stop(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        run.is_running = False
        run.state = OrchestratorState.IDLE
        run.current_stage = ""
        run.current_agent = ""
        run.current_action = "Stopped by user"
        self.save_db()
        return run

    def provide_human_decision(self, project_id: str, decision: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        project = self.projects.get(project_id)
        if not project:
            raise ValueError(f"Project '{project_id}' not found")

        decision_text = decision.strip()
        if project.constraints:
            project.constraints = f"{project.constraints}\n[User Specification]: {decision_text}"
        else:
            project.constraints = f"[User Specification]: {decision_text}"

        run.human_input_required = False
        run.human_decision_prompt = None
        run.human_decision_response = decision_text
        run.last_error = ""
        run.error_message = ""
        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.failed_stage = ""

        self.activity_store.setdefault(project_id, []).insert(0, {
            "agent": "Orchestrator",
            "action": "Human Decision Incorporated",
            "provider": "System Decision",
            "model": "Control Engine",
            "status": "completed",
            "duration_ms": 5,
            "summary": f"User provided decision: {decision_text}",
        })

        self.save_db()
        return run

    def continue_manually(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.last_error = ""
        run.error_message = ""
        run.failed_stage = ""
        run.current_action = "Continuing manually to Testing"

        self.activity_store.setdefault(project_id, []).insert(0, {
            "agent": "Orchestrator",
            "action": "Continue Manually Authorized",
            "provider": "System Decision",
            "model": "Control Engine",
            "status": "completed",
            "duration_ms": 5,
            "summary": "User authorized manual continuation past review findings to Testing.",
        })

        self.save_db()
        return run

    def invalidate_downstream(self, project_id: str, trigger_stage: str, reason: str) -> list[str]:
        run = self.get_or_create_run(project_id)
        invalidated: list[str] = []

        if trigger_stage in ("Architecture Agent", "Architecture"):
            invalidated = ["Execution Plan", "Review", "Testing"]
            self.plan_store.pop(project_id, None)
            self.review_store.pop(project_id, None)
            self.test_store.pop(project_id, None)
        elif trigger_stage in ("Planner Agent", "Execution Plan"):
            invalidated = ["Review", "Testing"]
            self.review_store.pop(project_id, None)
            self.test_store.pop(project_id, None)

        for stage in invalidated:
            if stage in run.completed_stages:
                run.completed_stages.remove(stage)

        if invalidated:
            rec = InvalidationRecord(
                timestamp=self.now_iso(),
                trigger_stage=trigger_stage,
                invalidated_stages=invalidated,
                reason=reason,
            )
            run.invalidation_history.append(rec)
            self.activity_store.setdefault(project_id, []).insert(0, {
                "agent": "Orchestrator",
                "action": "Invalidate Downstream Stages",
                "provider": "System Decision",
                "model": "Control Engine",
                "status": "completed",
                "duration_ms": 5,
                "summary": f"{trigger_stage} changed: invalidated {', '.join(invalidated)}. Reason: {reason}",
            })
            self.save_db()

        return invalidated

    def evaluate_review(
        self,
        project: ProjectContext,
        review: ReviewResponse,
        architecture: ArchitectureResponse | None,
        plan: PlannerResponse | None,
    ) -> tuple[str, str, list[dict[str, Any]], dict[str, Any] | None]:
        """Classify review findings deterministically into PASS, HUMAN_DECISION_REQUIRED, or CORRECTION_REQUIRED."""
        blocking_risks: list[dict[str, Any]] = []

        human_keywords = [
            "unspecified",
            "not specified",
            "missing specification",
            "requires user choice",
            "user decision",
            "human decision",
            "conflicting requirement",
            "contradictory requirement",
            "material selection required",
            "safety threshold unspecified",
            "clarification needed",
            "external approval required",
            "missing project information",
            "cannot be determined without user",
            "undefined parameter",
            "acceptance threshold is ambiguous",
        ]

        for r in review.risks:
            sev = str(r.severity).lower()
            text = f"{r.title} {r.detail} {r.recommendation}".lower()
            if sev in ("critical", "high"):
                # 1. Check for missing project information or required user choices
                if any(kw in text for kw in human_keywords):
                    question = r.recommendation or f"Please clarify: {r.title}"
                    if "unspecified" in text or "not specified" in text:
                        question = f"Clarify specification for '{r.title}': What threshold or parameter should be satisfied?"

                    prompt_data = {
                        "question": question,
                        "affected_stage": "Requirements",
                        "evidence": f"{r.title}: {r.detail}",
                        "mitigation": r.recommendation,
                    }
                    return "HUMAN_DECISION_REQUIRED", "Requirements", [r.model_dump()], prompt_data

                # 2. Check if actionable engineering blocker
                if sev == "critical":
                    blocking_risks.append(r.model_dump())
                elif sev == "high":
                    blocker_indicators = [
                        "blocker", "blocks implementation", "cannot proceed", "fatal", "prevents testing",
                        "no recovery", "offline recovery", "data loss", "unhandled failure", "missing component",
                        "deadlock", "shoot-through", "runaway", "unspecified", "contradiction",
                        "omission", "buffer overrun", "overflow", "missing dependency", "missing prerequisite",
                    ]
                    if any(kw in text for kw in blocker_indicators):
                        blocking_risks.append(r.model_dump())

        # If no blocking critical or high severity risks, it's a clean PASS
        if not blocking_risks:
            return "PASS", "", [], None

        # Determine earliest affected stage
        arch_comp_names = [c.name.lower() for c in (architecture.components if architecture else [])]
        arch_comp_ids = [c.id.lower() for c in (architecture.components if architecture else [])]

        arch_keywords = [
            "component", "subsystem", "hardware", "firmware", "schematic",
            "sensor", "actuator", "microcontroller", "pin", "protocol",
            "interface", "bus", "circuit", "topology", "payload",
            "connection", "spi", "i2c", "uart", "can-bus", "wifi", "wi-fi",
            "bluetooth", "ble", "mqtt", "recovery policy", "failover", "buffer overrun",
            "power supply", "adc", "dma", "dsp", "telemetry", "offline recovery",
        ]

        affects_architecture = False
        affects_planning = False

        for risk in blocking_risks:
            text = f"{risk.get('title', '')} {risk.get('detail', '')} {risk.get('recommendation', '')}".lower()
            for name in arch_comp_names:
                if name in text:
                    affects_architecture = True
                    break
            for cid in arch_comp_ids:
                if cid in text:
                    affects_architecture = True
                    break
            if any(kw in text for kw in arch_keywords):
                affects_architecture = True

            plan_keywords = ["task", "milestone", "schedule", "effort", "dependency", "timeline", "critical path"]
            if any(kw in text for kw in plan_keywords):
                affects_planning = True

        if affects_architecture:
            target = "Architecture Agent"
        elif affects_planning:
            target = "Planner Agent"
        else:
            target = "Architecture Agent"

        return "CORRECTION_REQUIRED", target, blocking_risks, None

    # =========================================================================
    # PHASE 3: ISSUE RECOVERY & REPLANNING
    # =========================================================================

    def classify_recovery(
        self,
        project: ProjectContext,
        analysis: IssueAnalysisResponse | dict,
        description: str = "",
    ) -> tuple[str, str, dict[str, Any]]:
        """Deterministically classifies an issue diagnosis into one of the 5 recovery types."""
        if isinstance(analysis, dict):
            analysis = IssueAnalysisResponse(**analysis)

        combined_text = (
            f"{analysis.issue_summary} "
            f"{' '.join(analysis.likely_causes)} "
            f"{' '.join(analysis.recommended_fix)} "
            f"{analysis.recommended_next_action} "
            f"{description}"
        ).lower()

        # 1. Check MANUAL_INTERVENTION_REQUIRED (Physical/Hardware defects)
        physical_keywords = [
            "physically damaged", "physical damage", "broken pcb", "damaged sensor", "burnt", "fried",
            "soldering", "hardware defect", "cable disconnected", "loose wire", "mechanical repair",
            "physical inspection", "component replacement", "replace sensor", "hardware repair",
            "replace hardware", "damaged hardware", "short circuit", "defective unit", "hardware failure"
        ]
        if any(kw in combined_text for kw in physical_keywords):
            prompt_data = {
                "likely_cause": analysis.likely_causes[0] if analysis.likely_causes else "Physical hardware defect detected",
                "recommended_action": analysis.recommended_fix[0] if analysis.recommended_fix else "Inspect and repair/replace physical hardware component.",
                "affected_components": analysis.affected_components or ["Hardware Sensor/PCB"],
                "verification_required": f"Verify component connectivity and sensor integrity after physical intervention for: {analysis.issue_summary}",
            }
            return "MANUAL_INTERVENTION_REQUIRED", "Hardware/Physical", prompt_data

        # 2. Check HUMAN_DECISION_REQUIRED (Unknown engineering parameters or missing user decisions)
        human_keywords = [
            "unspecified", "not specified", "missing specification", "requires user choice", "user decision",
            "human decision", "choose replacement", "cost increase", "safety threshold unspecified",
            "approve scope change", "alternative selection required", "user approval required", "tradeoff required"
        ]
        if any(kw in combined_text for kw in human_keywords):
            prompt_data = {
                "question": analysis.recommended_next_action or f"Clarify specification or decision for: {analysis.issue_summary}",
                "affected_stage": "Requirements",
                "evidence": f"Likely cause: {analysis.likely_causes[0] if analysis.likely_causes else ''}. Fix options: {', '.join(analysis.recommended_fix)}",
                "mitigation": ", ".join(analysis.recommended_fix),
            }
            return "HUMAN_DECISION_REQUIRED", "Requirements", prompt_data

        # 3. Check ARCHITECTURE_RECOVERY (Design-level flaw)
        arch_keywords = [
            "offline buffer", "storage", "buffer overrun", "ring buffer", "interface conflict",
            "communication boundary", "fail-safe", "redundancy", "architecture", "hardware design",
            "pinout", "protocol mismatch", "telemetry loss", "missing subsystem", "galvanic isolation",
            "circuit", "power rail", "isolation barrier"
        ]
        has_arch_component = bool(analysis.affected_components and len(analysis.affected_components) > 0)
        if any(kw in combined_text for kw in arch_keywords) or (has_arch_component and analysis.severity in ("critical", "high")):
            issue_dict = {
                "description": description or analysis.issue_summary,
                "likely_causes": analysis.likely_causes,
                "recommended_fix": analysis.recommended_fix,
                "affected_components": analysis.affected_components,
                "severity": str(analysis.severity),
            }
            return "ARCHITECTURE_RECOVERY", "Architecture Agent", issue_dict

        # 4. Check PLAN_RECOVERY (Planning / Task dependencies / Sequencing)
        plan_keywords = [
            "missing task", "dependency", "missing prerequisite", "sequencing", "schedule",
            "milestone", "prerequisite", "deadlock", "work breakdown", "task order", "timing"
        ]
        if analysis.recovery_task.needed or len(analysis.blocked_tasks) > 0 or any(kw in combined_text for kw in plan_keywords):
            issue_dict = {
                "description": description or analysis.issue_summary,
                "likely_causes": analysis.likely_causes,
                "recommended_fix": analysis.recommended_fix,
                "blocked_tasks": analysis.blocked_tasks,
                "recovery_task": analysis.recovery_task.model_dump(),
                "severity": str(analysis.severity),
            }
            return "PLAN_RECOVERY", "Planner Agent", issue_dict

        # 5. NO_ARTIFACT_CHANGE (Transient operational issue)
        issue_dict = {
            "description": description or analysis.issue_summary,
            "likely_causes": analysis.likely_causes,
            "recommended_fix": analysis.recommended_fix,
            "severity": str(analysis.severity),
        }
        return "NO_ARTIFACT_CHANGE", "Operational/Testing", issue_dict

    def start_issue_recovery(self, project_id: str, issue_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)

        # Concurrency safety: check if normal autonomous run is in progress
        if run.is_running and run.state == OrchestratorState.RUNNING and not run.active_issue_id:
            raise ValueError("Cannot start issue recovery while normal autonomous pipeline is running")

        run.active_issue_id = issue_id
        run.recovery_state = "DIAGNOSING"
        run.recovery_attempt = 0
        run.max_recovery_attempts = 2
        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.failed_stage = ""
        run.last_error = ""
        run.error_message = ""
        run.manual_intervention_required = False
        run.manual_intervention_prompt = None

        self.save_db()
        return run

    def confirm_manual_intervention(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        run.manual_intervention_required = False
        run.manual_intervention_prompt = None
        run.manual_intervention_completed = True
        run.recovery_state = "VERIFYING"
        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.last_error = ""
        run.error_message = ""

        self.activity_store.setdefault(project_id, []).insert(0, {
            "agent": "Orchestrator",
            "action": "Manual Intervention Confirmed",
            "provider": "System Decision",
            "model": "Control Engine",
            "status": "completed",
            "duration_ms": 5,
            "summary": "User confirmed manual intervention completed. Proceeding to verification.",
        })

        self.save_db()
        return run

    def retry_recovery(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        run.state = OrchestratorState.RUNNING
        run.is_running = True
        run.last_error = ""
        run.error_message = ""
        # Preserve failed_stage so recovery retries ONLY the failed stage
        run.recovery_state = "RECOVERING"
        self.save_db()
        return run

    def stop_recovery(self, project_id: str) -> OrchestratorRun:
        run = self.get_or_create_run(project_id)
        run.active_issue_id = ""
        run.recovery_state = "IDLE"
        run.is_running = False
        run.state = OrchestratorState.IDLE
        run.current_action = "Issue recovery stopped by user"
        self.save_db()
        return run

    async def run_issue_recovery_pipeline(self, project_id: str, issue_id: str) -> None:
        """Main Phase 3 issue recovery loop."""
        run = self.get_or_create_run(project_id)
        project = self.projects.get(project_id)
        if not project:
            run.state = OrchestratorState.FAILED
            run.is_running = False
            run.last_error = "Project context missing"
            self.save_db()
            return

        # Find target issue
        project_issues = self.issues_store.get(project_id, [])
        target_issue = next((iss for iss in project_issues if iss.id == issue_id), None)
        if not target_issue:
            run.state = OrchestratorState.FAILED
            run.is_running = False
            run.last_error = f"Issue '{issue_id}' not found"
            self.save_db()
            return

        run.recovery_state = "EVALUATING"
        run.active_issue_id = issue_id
        run.is_running = True
        run.state = OrchestratorState.RUNNING
        classification, target, prompt_data = self.classify_recovery(
            project, target_issue.analysis, target_issue.description
        )
        run.recovery_type = classification
        run.recovery_target = target

        self.activity_store.setdefault(project_id, []).insert(0, {
            "agent": "Orchestrator",
            "action": f"Classified Issue Recovery: {classification}",
            "provider": "System Decision",
            "model": "Control Engine",
            "status": "completed",
            "duration_ms": 5,
            "summary": f"Target: {target}. Issue: {target_issue.analysis.issue_summary}",
        })
        self.save_db()

        # ---------------------------------------------------------------------
        # BRANCH 1: MANUAL_INTERVENTION_REQUIRED
        # ---------------------------------------------------------------------
        if classification == "MANUAL_INTERVENTION_REQUIRED":
            if not getattr(run, "manual_intervention_completed", False):
                run.recovery_state = "AWAITING_MANUAL_INTERVENTION"
                run.manual_intervention_required = True
                run.manual_intervention_prompt = ManualInterventionPrompt(issue_id=issue_id, **prompt_data)
                run.state = OrchestratorState.PAUSED
                run.is_running = False
                run.last_error = f"Manual intervention required: {prompt_data.get('recommended_action')}"
                run.error_message = run.last_error
                self.save_db()
                return
            else:
                # Manual intervention confirmed: generate targeted verification
                run.recovery_state = "VERIFYING"
                run.current_action = "Generating post-intervention verification"
                self.save_db()

                reqs = self.requirements_store.get(project_id)
                arch = self.architecture_store.get(project_id)
                plan = self.plan_store.get(project_id)
                review = self.review_store.get(project_id)
                if reqs and arch:
                    try:
                        mem_ctx = self._retrieve_and_apply_memory(project, "Test Agent", run, issue_context=prompt_data)
                        test_analysis, test_duration = self.test_agent.analyze(
                            project, reqs, arch, plan=plan, review=review, issue_context=prompt_data, memory_context=mem_ctx
                        )
                        test_resp = TestResponse(
                            **test_analysis.model_dump(),
                            project_id=project_id,
                            provider="Nebius Token Factory",
                            model=self.test_agent.model,
                            duration_ms=test_duration,
                        )
                        self.test_store[project_id] = test_resp
                    except Exception as e:
                        logger.warning(f"Targeted post-intervention test verification failed: {e}")

                run.recovery_state = "RECOVERY_COMPLETED"
                run.state = OrchestratorState.COMPLETED
                run.is_running = False
                run.current_action = "RECOVERY COMPLETE - READY FOR VERIFICATION"
                target_issue.status = "Ready for Verification"

                rec = RecoveryRecord(
                    id=f"rec-{uuid.uuid4().hex[:6]}",
                    issue_id=issue_id,
                    timestamp=self.now_iso(),
                    classification=classification,
                    target=target,
                    summary=f"Manual intervention verified for: {target_issue.analysis.issue_summary}",
                    actions_taken=[
                        f"Manual intervention confirmed: {prompt_data.get('recommended_action')}",
                        "Post-intervention verification strategy generated",
                    ],
                    result="Success",
                )
                run.recovery_history.append(rec)
                try:
                    self._store_recovery_lesson(
                        project,
                        target_issue,
                        classification,
                        target,
                        rec.actions_taken,
                        "Post-intervention verification strategy generated",
                    )
                except Exception as e:
                    logger.warning(f"Failed to store recovery lesson: {e}")
                self.save_db()
                return

        # ---------------------------------------------------------------------
        # BRANCH 2: HUMAN_DECISION_REQUIRED
        # ---------------------------------------------------------------------
        if classification == "HUMAN_DECISION_REQUIRED":
            if not getattr(run, "human_decision_response", None):
                run.recovery_state = "AWAITING_HUMAN_DECISION"
                run.human_input_required = True
                run.human_decision_prompt = HumanDecisionPrompt(**prompt_data)
                run.state = OrchestratorState.PAUSED
                run.is_running = False
                run.last_error = f"Human decision required: {prompt_data.get('question')}"
                run.error_message = run.last_error
                self.save_db()
                return
            else:
                prompt_data["human_decision"] = getattr(run, "human_decision_response", "")

        # ---------------------------------------------------------------------
        # BRANCH 3: NO_ARTIFACT_CHANGE (Operational / Transient)
        # ---------------------------------------------------------------------
        if classification == "NO_ARTIFACT_CHANGE":
            run.recovery_state = "VERIFYING"
            run.current_action = "Generating operational verification"
            self.save_db()

            reqs = self.requirements_store.get(project_id)
            arch = self.architecture_store.get(project_id)
            plan = self.plan_store.get(project_id)
            review = self.review_store.get(project_id)

            if reqs and arch:
                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Test Agent", run, issue_context=prompt_data)
                    test_analysis, test_duration = self.test_agent.analyze(
                        project, reqs, arch, plan=plan, review=review, issue_context=prompt_data, memory_context=mem_ctx
                    )
                    test_resp = TestResponse(
                        **test_analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.test_agent.model,
                        duration_ms=test_duration,
                    )
                    self.test_store[project_id] = test_resp
                except Exception as e:
                    logger.warning(f"Targeted test verification failed: {e}")

            run.recovery_state = "RECOVERY_COMPLETED"
            run.state = OrchestratorState.COMPLETED
            run.is_running = False
            run.current_action = "RECOVERY COMPLETE - READY FOR VERIFICATION"
            target_issue.status = "Ready for Verification"

            rec = RecoveryRecord(
                id=f"rec-{uuid.uuid4().hex[:6]}",
                issue_id=issue_id,
                timestamp=self.now_iso(),
                classification=classification,
                target=target,
                summary=f"Operational resolution confirmed for: {target_issue.analysis.issue_summary}",
                actions_taken=["Operational recovery recorded", "Targeted verification strategy confirmed"],
                result="Success",
            )
            run.recovery_history.append(rec)
            try:
                self._store_recovery_lesson(
                    project,
                    target_issue,
                    classification,
                    target,
                    rec.actions_taken,
                    "Targeted verification strategy confirmed",
                )
            except Exception as e:
                logger.warning(f"Failed to store recovery lesson: {e}")
            self.save_db()
            return

        # ---------------------------------------------------------------------
        # BRANCH 4: ARCHITECTURE_RECOVERY & PLAN_RECOVERY (Bounded Loop <= 2)
        # ---------------------------------------------------------------------
        while run.recovery_attempt < run.max_recovery_attempts and run.is_running:
            if not run.failed_stage:
                run.recovery_attempt += 1
            run.recovery_state = "RECOVERING"
            self.save_db()

            reqs = self.requirements_store.get(project_id)
            if not reqs:
                self._handle_failure(run, project_id, "Requirement Agent", "Requirements", RuntimeError("Requirements missing"))
                return

            arch_resp = self.architecture_store.get(project_id)
            plan_resp = self.plan_store.get(project_id)

            if classification == "ARCHITECTURE_RECOVERY":
                arch_resp = self.architecture_store.get(project_id)
                # Check if architecture was already recovered and failure occurred at Planner
                arch_already_recovered = (
                    arch_resp is not None
                    and "Architecture" in run.completed_stages
                    and run.failed_stage in ("Planner Agent", "Execution Plan")
                )

                if not arch_already_recovered:
                    self.invalidate_downstream(project_id, "Architecture Agent", f"Issue recovery: {target_issue.analysis.issue_summary}")
                    existing_arch = self.architecture_store.get(project_id)

                    run.current_stage = "Architecture"
                    run.current_agent = "Architecture Agent"
                    run.current_action = f"Recovering Architecture (Attempt {run.recovery_attempt})"
                    self.save_db()

                    try:
                        mem_ctx = self._retrieve_and_apply_memory(project, "Architecture Agent", run, issue_context=prompt_data)
                        corr_arch, dur_arch = self.architecture_agent.analyze(
                            project, reqs, existing_architecture=existing_arch, issue_context=prompt_data, memory_context=mem_ctx
                        )
                        arch_resp = ArchitectureResponse(
                            **corr_arch.model_dump(),
                            project_id=project_id,
                            provider="Nebius Token Factory",
                            model=self.architecture_agent.model,
                            duration_ms=dur_arch,
                        )
                        self.architecture_store[project_id] = arch_resp
                        self.activity_store.setdefault(project_id, []).insert(0, {
                            "agent": "Architecture Agent",
                            "action": f"Recover Architecture (Attempt {run.recovery_attempt})",
                            "provider": "Nebius Token Factory",
                            "model": self.architecture_agent.model,
                            "status": "completed",
                            "duration_ms": dur_arch,
                            "summary": f"Revised architecture for issue: {corr_arch.summary}",
                        })
                        if "Architecture" not in run.completed_stages:
                            run.completed_stages.append("Architecture")
                        run.execution_count += 1
                        self.save_db()
                    except Exception as e:
                        self._handle_failure(run, project_id, "Architecture Agent", "Architecture Recovery", e)
                        return
                else:
                    logger.info("Preserving already recovered Architecture; retrying only Planner Agent")

                # Regenerate Plan downstream
                run.failed_stage = ""
                run.current_stage = "Execution Plan"
                run.current_agent = "Planner Agent"
                run.current_action = "Regenerating Execution Plan"
                self.save_db()

                existing_plan = self.plan_store.get(project_id)
                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Planner Agent", run, issue_context=prompt_data)
                    plan_analysis, plan_dur = self.planner_agent.analyze(
                        project, reqs, arch_resp, existing_plan=existing_plan, issue_context=prompt_data, memory_context=mem_ctx
                    )
                    plan_resp = PlannerResponse(
                        **plan_analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.planner_agent.model,
                        duration_ms=plan_dur,
                    )
                    self.plan_store[project_id] = plan_resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Planner Agent",
                        "action": "Regenerate Plan for Issue Recovery",
                        "provider": "Nebius Token Factory",
                        "model": self.planner_agent.model,
                        "status": "completed",
                        "duration_ms": plan_dur,
                        "summary": f"Plan updated with recovery tasks: {plan_analysis.summary}",
                    })
                    if "Execution Plan" not in run.completed_stages:
                        run.completed_stages.append("Execution Plan")
                    run.execution_count += 1
                    self.save_db()
                except Exception as e:
                    self._handle_failure(run, project_id, "Planner Agent", "Plan Regeneration", e)
                    return

            elif classification in ("PLAN_RECOVERY", "HUMAN_DECISION_REQUIRED"):
                self.invalidate_downstream(project_id, "Planner Agent", f"Issue recovery: {target_issue.analysis.issue_summary}")
                existing_plan = self.plan_store.get(project_id)
                arch_resp = self.architecture_store.get(project_id)
                if not arch_resp:
                    self._handle_failure(run, project_id, "Planner Agent", "Plan Recovery", RuntimeError("Architecture missing"))
                    return

                run.current_stage = "Execution Plan"
                run.current_agent = "Planner Agent"
                run.current_action = f"Recovering Execution Plan (Attempt {run.recovery_attempt})"
                self.save_db()

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Planner Agent", run, issue_context=prompt_data)
                    plan_analysis, plan_dur = self.planner_agent.analyze(
                        project, reqs, arch_resp, existing_plan=existing_plan, issue_context=prompt_data, memory_context=mem_ctx
                    )
                    plan_resp = PlannerResponse(
                        **plan_analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.planner_agent.model,
                        duration_ms=plan_dur,
                    )
                    self.plan_store[project_id] = plan_resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Planner Agent",
                        "action": f"Recover Execution Plan (Attempt {run.recovery_attempt})",
                        "provider": "Nebius Token Factory",
                        "model": self.planner_agent.model,
                        "status": "completed",
                        "duration_ms": plan_dur,
                        "summary": f"Plan updated with recovery tasks: {plan_analysis.summary}",
                    })
                    if "Execution Plan" not in run.completed_stages:
                        run.completed_stages.append("Execution Plan")
                    run.execution_count += 1
                    self.save_db()
                except Exception as e:
                    self._handle_failure(run, project_id, "Planner Agent", "Plan Recovery", e)
                    return

            # Re-review system
            run.recovery_state = "REVIEWING"
            run.current_stage = "Review"
            run.current_agent = "Reviewer Agent"
            run.current_action = "Re-reviewing System Post-Recovery"
            self.save_db()

            try:
                mem_ctx = self._retrieve_and_apply_memory(project, "Reviewer Agent", run, issue_context=prompt_data)
                rev_analysis, rev_dur = self.reviewer_agent.analyze(project, reqs, arch_resp, plan=plan_resp, memory_context=mem_ctx)
                rev_resp = ReviewResponse(
                    **rev_analysis.model_dump(),
                    project_id=project_id,
                    provider="Nebius Token Factory",
                    model=self.reviewer_agent.model,
                    duration_ms=rev_dur,
                )
                self.review_store[project_id] = rev_resp
                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Reviewer Agent",
                    "action": "Re-review System Post-Recovery",
                    "provider": "Nebius Token Factory",
                    "model": self.reviewer_agent.model,
                    "status": "completed",
                    "duration_ms": rev_dur,
                    "summary": f"Re-review complete: {len(rev_analysis.risks)} risks assessed",
                })
                if "Review" not in run.completed_stages:
                    run.completed_stages.append("Review")
                run.execution_count += 1
                self.save_db()
            except Exception as e:
                self._handle_failure(run, project_id, "Reviewer Agent", "Re-review Post-Recovery", e)
                return

            # Evaluate review
            decision, _, blocking, _ = self.evaluate_review(project, rev_resp, arch_resp, plan_resp)
            if decision == "PASS":
                # Generate targeted verification strategy
                run.recovery_state = "VERIFYING"
                run.current_stage = "Testing"
                run.current_agent = "Test Agent"
                run.current_action = "Generating Targeted Issue Verification"
                self.save_db()

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Test Agent", run, issue_context=prompt_data)
                    test_analysis, test_dur = self.test_agent.analyze(
                        project, reqs, arch_resp, plan=plan_resp, review=rev_analysis, issue_context=prompt_data, memory_context=mem_ctx
                    )
                    test_resp = TestResponse(
                        **test_analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.test_agent.model,
                        duration_ms=test_dur,
                    )
                    self.test_store[project_id] = test_resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Test Agent",
                        "action": "Generate Targeted Verification Strategy",
                        "provider": "Nebius Token Factory",
                        "model": self.test_agent.model,
                        "status": "completed",
                        "duration_ms": test_dur,
                        "summary": f"{len(test_analysis.test_cases)} targeted verification scenarios generated",
                    })
                    if "Testing" not in run.completed_stages:
                        run.completed_stages.append("Testing")
                    run.execution_count += 1
                except Exception as e:
                    self._handle_failure(run, project_id, "Test Agent", "Verification Generation", e)
                    return

                run.recovery_state = "RECOVERY_COMPLETED"
                run.state = OrchestratorState.COMPLETED
                run.is_running = False
                run.current_action = "RECOVERY COMPLETE - READY FOR VERIFICATION"
                target_issue.status = "Ready for Verification"

                rec = RecoveryRecord(
                    id=f"rec-{uuid.uuid4().hex[:6]}",
                    issue_id=issue_id,
                    timestamp=self.now_iso(),
                    classification=classification,
                    target=target,
                    summary=f"Resolved issue: {target_issue.analysis.issue_summary}",
                    actions_taken=[
                        f"{target} revised",
                        "Plan updated",
                        "Re-review passed",
                        "Targeted verification strategy generated",
                    ],
                    result="Success",
                )
                run.recovery_history.append(rec)
                try:
                    self._store_recovery_lesson(
                        project,
                        target_issue,
                        classification,
                        target,
                        rec.actions_taken,
                        f"Verified by Test Agent: {len(test_analysis.test_cases)} scenarios",
                    )
                except Exception as e:
                    logger.warning(f"Failed to store recovery lesson: {e}")
                self.save_db()
                return

            else:
                # If still unresolved and reached maximum limit, pause
                if run.recovery_attempt >= run.max_recovery_attempts:
                    run.recovery_state = "RECOVERY_FAILED"
                    run.state = OrchestratorState.PAUSED
                    run.is_running = False
                    run.last_error = f"Issue remains unresolved after {run.max_recovery_attempts} autonomous recovery attempts."
                    run.error_message = run.last_error
                    run.unresolved_findings = blocking
                    self.save_db()
                    return

    # =========================================================================
    # PHASE 1 & 2 PIPELINE
    # =========================================================================

    async def run_pipeline(self, project_id: str) -> None:
        """Main autonomous execution and self-correction loop."""
        run = self.get_or_create_run(project_id)
        project = self.projects.get(project_id)
        if not project:
            run.state = OrchestratorState.FAILED
            run.is_running = False
            run.last_error = "Project context missing"
            run.error_message = "Project context missing"
            self.save_db()
            return

        max_total_specialist_executions = 15

        while run.is_running and run.state == OrchestratorState.RUNNING:
            if run.execution_count >= max_total_specialist_executions:
                run.state = OrchestratorState.PAUSED
                run.is_running = False
                run.last_error = f"Safety execution limit ({max_total_specialist_executions}) reached."
                run.error_message = run.last_error
                self.save_db()
                break

            # 1. REQUIREMENTS STAGE
            if not self.requirements_store.get(project_id):
                run.current_stage = "Requirements"
                run.current_agent = "Requirement Agent"
                run.current_action = "Running Requirement Agent"
                self.save_db()

                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Orchestrator",
                    "action": "Selected Requirement Agent",
                    "provider": "System Decision",
                    "model": "Control Engine",
                    "status": "completed",
                    "duration_ms": 5,
                    "summary": "Autonomous progression to Requirements",
                })

                try:
                    analysis, duration_ms = requirement_agent.analyze(project)
                    resp = RequirementsResponse(
                        **analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=requirement_agent.model,
                        duration_ms=duration_ms,
                        summary=f"{len(analysis.functional_requirements)} functional and {len(analysis.non_functional_requirements)} non-functional requirements identified",
                    )
                    self.requirements_store[project_id] = resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Requirement Agent",
                        "action": "Analyze Requirements",
                        "provider": "Nebius Token Factory",
                        "model": requirement_agent.model,
                        "status": "completed",
                        "duration_ms": duration_ms,
                        "summary": resp.summary,
                    })
                    if "Requirements" not in run.completed_stages:
                        run.completed_stages.append("Requirements")
                    run.execution_count += 1
                    self.save_db()
                    await asyncio.sleep(0.5)
                    continue
                except Exception as e:
                    self._handle_failure(run, project_id, "Requirement Agent", "Requirements", e)
                    return

            # 2. ARCHITECTURE STAGE
            if not self.architecture_store.get(project_id):
                reqs = self.requirements_store.get(project_id)
                if not reqs:
                    self._handle_failure(run, project_id, "Architecture Agent", "Architecture", RuntimeError("Requirements missing"))
                    return

                run.current_stage = "Architecture"
                run.current_agent = "Architecture Agent"
                run.current_action = "Running Architecture Agent"
                self.save_db()

                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Orchestrator",
                    "action": "Selected Architecture Agent",
                    "provider": "System Decision",
                    "model": "Control Engine",
                    "status": "completed",
                    "duration_ms": 5,
                    "summary": "Autonomous progression to Architecture",
                })

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Architecture Agent", run)
                    analysis, duration_ms = self.architecture_agent.analyze(project, reqs, memory_context=mem_ctx)
                    resp = ArchitectureResponse(
                        **analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.architecture_agent.model,
                        duration_ms=duration_ms,
                    )
                    self.architecture_store[project_id] = resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Architecture Agent",
                        "action": "Generate Architecture",
                        "provider": "Nebius Token Factory",
                        "model": self.architecture_agent.model,
                        "status": "completed",
                        "duration_ms": duration_ms,
                        "summary": analysis.summary,
                    })
                    if "Architecture" not in run.completed_stages:
                        run.completed_stages.append("Architecture")
                    run.execution_count += 1
                    self.save_db()
                    await asyncio.sleep(0.5)
                    continue
                except Exception as e:
                    self._handle_failure(run, project_id, "Architecture Agent", "Architecture", e)
                    return

            # 3. PLANNER STAGE
            if not self.plan_store.get(project_id):
                reqs = self.requirements_store.get(project_id)
                arch = self.architecture_store.get(project_id)
                if not reqs or not arch:
                    self._handle_failure(run, project_id, "Planner Agent", "Execution Plan", RuntimeError("Requirements or Architecture missing"))
                    return

                run.current_stage = "Execution Plan"
                run.current_agent = "Planner Agent"
                run.current_action = "Running Planner Agent"
                self.save_db()

                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Orchestrator",
                    "action": "Selected Planner Agent",
                    "provider": "System Decision",
                    "model": "Control Engine",
                    "status": "completed",
                    "duration_ms": 5,
                    "summary": "Autonomous progression to Execution Plan",
                })

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Planner Agent", run)
                    analysis, duration_ms = self.planner_agent.analyze(project, reqs, arch, memory_context=mem_ctx)
                    resp = PlannerResponse(
                        **analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.planner_agent.model,
                        duration_ms=duration_ms,
                    )
                    self.plan_store[project_id] = resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Planner Agent",
                        "action": "Generate Execution Plan",
                        "provider": "Nebius Token Factory",
                        "model": self.planner_agent.model,
                        "status": "completed",
                        "duration_ms": duration_ms,
                        "summary": analysis.summary,
                    })
                    if "Execution Plan" not in run.completed_stages:
                        run.completed_stages.append("Execution Plan")
                    run.execution_count += 1
                    self.save_db()
                    await asyncio.sleep(0.5)
                    continue
                except Exception as e:
                    self._handle_failure(run, project_id, "Planner Agent", "Execution Plan", e)
                    return

            # 4. REVIEWER STAGE & EVALUATION
            if not self.review_store.get(project_id):
                reqs = self.requirements_store.get(project_id)
                arch = self.architecture_store.get(project_id)
                plan = self.plan_store.get(project_id)
                if not reqs or not arch:
                    self._handle_failure(run, project_id, "Reviewer Agent", "Review", RuntimeError("Requirements or Architecture missing"))
                    return

                action_label = "Re-reviewing System" if run.correction_count > 0 else "Running Reviewer Agent"
                run.current_stage = "Review"
                run.current_agent = "Reviewer Agent"
                run.current_action = action_label
                self.save_db()

                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Orchestrator",
                    "action": "Selected Reviewer Agent",
                    "provider": "System Decision",
                    "model": "Control Engine",
                    "status": "completed",
                    "duration_ms": 5,
                    "summary": f"Autonomous progression to Review (Iteration {run.review_iteration})",
                })

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Reviewer Agent", run)
                    analysis, duration_ms = self.reviewer_agent.analyze(project, reqs, arch, plan=plan, memory_context=mem_ctx)
                    resp = ReviewResponse(
                        **analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.reviewer_agent.model,
                        duration_ms=duration_ms,
                    )
                    self.review_store[project_id] = resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Reviewer Agent",
                        "action": "Run Project Review",
                        "provider": "Nebius Token Factory",
                        "model": self.reviewer_agent.model,
                        "status": "completed",
                        "duration_ms": duration_ms,
                        "summary": f"Identified {len(analysis.risks)} engineering risks/gaps",
                    })
                    if "Review" not in run.completed_stages:
                        run.completed_stages.append("Review")
                    run.execution_count += 1
                    self.save_db()

                    # EVALUATE REVIEW FINDINGS
                    decision, target, blocking_findings, human_prompt = self.evaluate_review(project, resp, arch, plan)
                    run.review_decision = decision
                    run.unresolved_findings = blocking_findings

                    if decision == "PASS":
                        run.unresolved_findings = []
                        if run.correction_count > 0 and getattr(run, "_last_corrected_findings", None):
                            try:
                                self._store_self_correction_lesson(
                                    project,
                                    run.correction_target,
                                    run._last_corrected_findings,
                                    f"Autonomous self-correction succeeded after {run.correction_count} cycles",
                                )
                            except Exception as e:
                                logger.warning(f"Failed to store self-correction lesson: {e}")

                        self.activity_store.setdefault(project_id, []).insert(0, {
                            "agent": "Orchestrator",
                            "action": "Review Evaluation: PASS",
                            "provider": "System Decision",
                            "model": "Control Engine",
                            "status": "completed",
                            "duration_ms": 5,
                            "summary": f"Review passed with no blocking issues (Self-corrections: {run.correction_count}). Proceeding to Testing.",
                        })
                        self.save_db()
                        await asyncio.sleep(0.5)
                        continue

                    elif decision == "HUMAN_DECISION_REQUIRED":
                        run.state = OrchestratorState.PAUSED
                        run.is_running = False
                        run.human_input_required = True
                        run.human_decision_prompt = HumanDecisionPrompt(**(human_prompt or {}))
                        run.last_error = f"Human decision required: {(human_prompt or {}).get('question', '')}"
                        run.error_message = run.last_error
                        run.failed_stage = "Requirements"
                        self.activity_store.setdefault(project_id, []).insert(0, {
                            "agent": "Orchestrator",
                            "action": "Review Evaluation: HUMAN_DECISION_REQUIRED",
                            "provider": "System Decision",
                            "model": "Control Engine",
                            "status": "completed",
                            "duration_ms": 5,
                            "summary": f"Human decision required: {(human_prompt or {}).get('question', '')}",
                        })
                        self.save_db()
                        return

                    elif decision == "CORRECTION_REQUIRED":
                        if run.correction_count >= run.max_corrections:
                            run.state = OrchestratorState.PAUSED
                            run.is_running = False
                            run.last_error = f"Reviewer feedback remains unresolved after maximum self-correction attempts ({run.max_corrections})."
                            run.error_message = run.last_error
                            run.failed_stage = target
                            self.activity_store.setdefault(project_id, []).insert(0, {
                                "agent": "Orchestrator",
                                "action": "Self-Correction Paused (Max Limit Reached)",
                                "provider": "System Decision",
                                "model": "Control Engine",
                                "status": "completed",
                                "duration_ms": 5,
                                "summary": f"Max correction cycles ({run.max_corrections}) reached with unresolved findings.",
                            })
                            self.save_db()
                            return

                        run.correction_count += 1
                        run.correction_cycles = run.correction_count
                        run.review_iteration += 1
                        run.correction_target = target
                        run._last_corrected_findings = blocking_findings

                        top_finding = blocking_findings[0]
                        self.activity_store.setdefault(project_id, []).insert(0, {
                            "agent": "Orchestrator",
                            "action": "Autonomous Decision: CORRECTION_REQUIRED",
                            "provider": "System Decision",
                            "model": "Control Engine",
                            "status": "completed",
                            "duration_ms": 5,
                            "summary": f"Correction cycle {run.correction_count}/{run.max_corrections}: Correcting {target}. Reason: {top_finding.get('title')}",
                        })

                        if target == "Architecture Agent":
                            self.invalidate_downstream(project_id, "Architecture Agent", f"Review risk: {top_finding.get('title')}")
                            existing_arch = self.architecture_store.pop(project_id, None)
                            if "Architecture" in run.completed_stages:
                                run.completed_stages.remove("Architecture")

                            run.current_stage = "Architecture"
                            run.current_agent = "Architecture Agent"
                            run.current_action = f"Correcting Architecture (Cycle {run.correction_count})"
                            self.save_db()

                            mem_ctx = self._retrieve_and_apply_memory(project, "Architecture Agent", run)
                            corr_analysis, corr_duration = self.architecture_agent.analyze(
                                project, reqs, existing_architecture=existing_arch, reviewer_findings=blocking_findings, memory_context=mem_ctx
                            )
                            arch_resp = ArchitectureResponse(
                                **corr_analysis.model_dump(),
                                project_id=project_id,
                                provider="Nebius Token Factory",
                                model=self.architecture_agent.model,
                                duration_ms=corr_duration,
                            )
                            self.architecture_store[project_id] = arch_resp
                            self.activity_store.setdefault(project_id, []).insert(0, {
                                "agent": "Architecture Agent",
                                "action": f"Correct Architecture (Cycle {run.correction_count})",
                                "provider": "Nebius Token Factory",
                                "model": self.architecture_agent.model,
                                "status": "completed",
                                "duration_ms": corr_duration,
                                "summary": f"Revised architecture resolving reviewer findings: {corr_analysis.summary}",
                            })
                            run.completed_stages.append("Architecture")
                            run.execution_count += 1
                            self.save_db()
                            await asyncio.sleep(0.5)
                            continue

                        elif target == "Planner Agent":
                            self.invalidate_downstream(project_id, "Planner Agent", f"Review risk: {top_finding.get('title')}")
                            existing_plan = self.plan_store.pop(project_id, None)
                            if "Execution Plan" in run.completed_stages:
                                run.completed_stages.remove("Execution Plan")

                            run.current_stage = "Execution Plan"
                            run.current_agent = "Planner Agent"
                            run.current_action = f"Correcting Execution Plan (Cycle {run.correction_count})"
                            self.save_db()

                            mem_ctx = self._retrieve_and_apply_memory(project, "Planner Agent", run)
                            corr_plan_analysis, corr_plan_duration = self.planner_agent.analyze(
                                project, reqs, arch, existing_plan=existing_plan, reviewer_findings=blocking_findings, memory_context=mem_ctx
                            )
                            plan_resp = PlannerResponse(
                                **corr_plan_analysis.model_dump(),
                                project_id=project_id,
                                provider="Nebius Token Factory",
                                model=self.planner_agent.model,
                                duration_ms=corr_plan_duration,
                            )
                            self.plan_store[project_id] = plan_resp
                            self.activity_store.setdefault(project_id, []).insert(0, {
                                "agent": "Planner Agent",
                                "action": f"Correct Execution Plan (Cycle {run.correction_count})",
                                "provider": "Nebius Token Factory",
                                "model": self.planner_agent.model,
                                "status": "completed",
                                "duration_ms": corr_plan_duration,
                                "summary": f"Revised plan resolving reviewer findings: {corr_plan_analysis.summary}",
                            })
                            run.completed_stages.append("Execution Plan")
                            run.execution_count += 1
                            self.save_db()
                            await asyncio.sleep(0.5)
                            continue

                except Exception as e:
                    self._handle_failure(run, project_id, "Reviewer Agent", "Review", e)
                    return

            # 5. TEST STAGE
            if not self.test_store.get(project_id):
                reqs = self.requirements_store.get(project_id)
                arch = self.architecture_store.get(project_id)
                plan = self.plan_store.get(project_id)
                review = self.review_store.get(project_id)
                if not reqs or not arch:
                    self._handle_failure(run, project_id, "Test Agent", "Testing", RuntimeError("Requirements or Architecture missing"))
                    return

                run.current_stage = "Testing"
                run.current_agent = "Test Agent"
                run.current_action = "Running Test Agent"
                self.save_db()

                self.activity_store.setdefault(project_id, []).insert(0, {
                    "agent": "Orchestrator",
                    "action": "Selected Test Agent",
                    "provider": "System Decision",
                    "model": "Control Engine",
                    "status": "completed",
                    "duration_ms": 5,
                    "summary": "Autonomous progression to Verification & Testing",
                })

                try:
                    mem_ctx = self._retrieve_and_apply_memory(project, "Test Agent", run)
                    analysis, duration_ms = self.test_agent.analyze(project, reqs, arch, plan=plan, review=review, memory_context=mem_ctx)
                    resp = TestResponse(
                        **analysis.model_dump(),
                        project_id=project_id,
                        provider="Nebius Token Factory",
                        model=self.test_agent.model,
                        duration_ms=duration_ms,
                    )
                    self.test_store[project_id] = resp
                    self.activity_store.setdefault(project_id, []).insert(0, {
                        "agent": "Test Agent",
                        "action": "Generate Verification Strategy",
                        "provider": "Nebius Token Factory",
                        "model": self.test_agent.model,
                        "status": "completed",
                        "duration_ms": duration_ms,
                        "summary": f"{len(analysis.test_cases)} verification scenarios generated",
                    })
                    if "Testing" not in run.completed_stages:
                        run.completed_stages.append("Testing")
                    run.execution_count += 1
                    self.save_db()
                    await asyncio.sleep(0.5)
                    continue
                except Exception as e:
                    self._handle_failure(run, project_id, "Test Agent", "Testing", e)
                    return

            # 6. PIPELINE COMPLETION
            all_done = all(s[0] in run.completed_stages for s in STAGE_SEQUENCE)
            if all_done and run.state != OrchestratorState.PAUSED:
                run.state = OrchestratorState.COMPLETED
                run.is_running = False
                run.current_stage = ""
                run.current_agent = ""
                run.current_action = "PROJECT READY FOR EXECUTION"
                run.completed_at = self.now_iso()
                self.save_db()
                break

    def _handle_failure(
        self,
        run: OrchestratorRun,
        project_id: str,
        agent_name: str,
        stage_name: str,
        error: Exception,
    ) -> None:
        logger.error(f"Orchestrator stage '{stage_name}' failed: {error}", exc_info=True)
        run.state = OrchestratorState.PAUSED
        run.is_running = False
        run.failed_stage = agent_name
        run.last_error = str(error)
        run.error_message = str(error)
        run.current_action = f"Paused due to {agent_name} error"

        self.activity_store.setdefault(project_id, []).insert(0, {
            "agent": agent_name,
            "action": f"Autonomous {stage_name}",
            "provider": "Nebius Token Factory",
            "model": "nvidia/Nemotron-3-Ultra-550b-a55b",
            "status": "failed",
            "duration_ms": 0,
            "summary": str(error),
        })
        self.save_db()
