import { useEffect, useState } from 'react'
import { AlertTriangle, ArrowRight, Check, CircleDot, RefreshCw } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { initializationService, type InitializationAgentProgress, type InitializationStatus } from '../services/initializationService'
import { projectService } from '../services/projectService'
import type { Project } from '../types'

const agentLabels: Record<InitializationAgentProgress['agent'], string> = { requirements: 'Requirement Agent', architecture: 'Architecture Agent', planner: 'Planner Agent', reviewer: 'Reviewer Agent', testing: 'Test Agent' }
const waitingText: Record<InitializationAgentProgress['agent'], string> = { requirements: 'Reading project context', architecture: 'Waiting for requirements', planner: 'Waiting for architecture', reviewer: 'Waiting for project plan', testing: 'Waiting for engineering context' }

export function InitializationPage({ project }: { project: Project }) { const navigate = useNavigate(); const [status, setStatus] = useState<InitializationStatus>(() => initializationService.get_status(project.id)); const [started, setStarted] = useState(false); useEffect(() => { if (project.id === 'smart-helmet') { initializationService.initialize_project(project.id).then(setStatus); return } if (status.status === 'CREATED' && !started) { setStarted(true); initializationService.initialize_project(project.id).then(setStatus) } }, [project.id, started, status.status]); useEffect(() => { if (status.status === 'READY' || status.status === 'FAILED' || project.id === 'smart-helmet') return; const timer = window.setInterval(() => setStatus(initializationService.get_status(project.id)), 250); return () => window.clearInterval(timer) }, [project.id, status.status]); const current = status.agents.find(agent => agent.status === 'RUNNING'); const latestProject = projectService.getProject(project.id) || project; if (status.status === 'READY') return <ReadyState project={latestProject} onOpen={() => navigate(`/project/${project.id}`)} />; if (status.status === 'FAILED') return <FailureState project={project} onRetry={() => { setStarted(true); initializationService.retry(project.id).then(setStatus) }} />; return <div className="initialization-page"><div className="initialization-heading"><span className="eyebrow">PROJECT INITIALIZATION · {project.name}</span><h1>Setting up your engineering workspace<span className="ellipsis">...</span></h1><p>ProjectPilot is activating a dependency-aware engineering team. Each agent receives the persisted output from the previous stage.</p></div><div className="initialization-progress panel"><div><span className="eyebrow">INITIALIZATION PROGRESS</span><strong>{status.progress}%</strong></div><div className="progress"><span style={{ width: `${status.progress}%` }} /></div><span className="initialization-current">{current ? `${agentLabels[current.agent]} is active` : 'Preparing the first agent'}</span></div><div className="initialization-agents">{status.agents.map(agent => <AgentStep key={agent.agent} agent={agent} />)}</div></div> }
function AgentStep({ agent }: { agent: InitializationAgentProgress }) { const running = agent.status === 'RUNNING'; const complete = agent.status === 'COMPLETED'; const failed = agent.status === 'FAILED' || agent.status === 'BLOCKED'; return <div className={`initialization-agent panel ${running ? 'running' : ''} ${failed ? 'failed' : ''}`}><span className={`initialization-icon ${complete ? 'complete' : ''}`}>{complete ? <Check size={17} /> : failed ? <AlertTriangle size={16} /> : running ? <RefreshCw className="spin" size={16} /> : <CircleDot size={16} />}</span><div><strong>{agentLabels[agent.agent]}</strong><span>{agent.summary || (running ? waitingText[agent.agent].replace('Waiting for', 'Designing') + '...' : waitingText[agent.agent])}</span></div><small>{agent.status}</small></div> }
function ReadyState({ project, onOpen }: { project: Project; onOpen: () => void }) { return <div className="initialization-page ready-state"><span className="badge badge-lime">PROJECT WORKSPACE READY</span><h1>Your engineering workspace is ready.</h1><p>ProjectPilot transformed your project context into structured engineering artifacts.</p><div className="ready-metrics">{[[project.requirements.length, 'Requirements'], [project.architecture.length, 'Architecture Components'], [project.tasks.length, 'Execution Tasks'], [project.risks.length, 'Engineering Risks'], [project.tests.length, 'Test Cases']].map(([value, label]) => <div className="panel" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><div className="ready-next panel"><span className="eyebrow">NEXT RECOMMENDED ACTION</span><h2>{project.nextAction.title}</h2><p>{project.nextAction.description}</p><div><span className="badge badge-high">{project.nextAction.priority}</span><span>{project.nextAction.effort}</span></div><button className="btn" onClick={onOpen}>Open Workspace <ArrowRight size={16} /></button></div></div> }
function FailureState({ project, onRetry }: { project: Project; onRetry: () => void }) { const status = initializationService.get_status(project.id); return <div className="initialization-page failure-state"><span className="badge badge-high">INITIALIZATION FAILED</span><h1>Project setup needs attention.</h1><p>{status.error || 'The agent pipeline could not complete this stage. Previously completed outputs are safe.'}</p><div className="initialization-agents">{status.agents.map(agent => <AgentStep agent={agent} key={agent.agent} />)}</div><button className="btn" onClick={onRetry}><RefreshCw size={16} />Retry Initialization</button></div> }
